### PR TITLE
Nuke Missile defense no longer attack the UEF COM Spy Satellite

### PR DESCRIPTION
**Pull request by Uveso**
issue #193

With unleashed nuke defenses can attack the artemis satellite. But they
also killed the Spy Sat from UEF Commander. Now they only attack the
Artemis Sat

### CODE REVIEW

**Comment by aeoncleanse** [comment]
They should probably kill all sats but the spy. So Novax should be hit too I think.

**Comment by aeoncleanse** [comment]
Anything with a weapon.

**Comment by Uveso** [comment]
No. You can easy defend against the novax with a single T3 shield.
In compare with the artemis, the Novax has no weapon.
But if the artemis sat is comming...you are in trouble.

**Comment by Uveso** [comment]
Maybe after merging https://github.com/FAForever/fa/pull/759 this could be an option.
But in my eyes the novax is to weak that we need a defense against it exept shields.

**Comment by aeoncleanse** [comment]
We're going to allow Novax to be hit, so I'm taking the inverse approach

**Pull request closed without merging**
