### PR TITLE
Fixed unit Display Abilities

### PR DESCRIPTION
**Pull request by Uveso**
#99

Update Display Abilities from all units.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Rebase please! :)

**Comment by aeoncleanse** [comment]
Closed because?

**Comment by aeoncleanse** [comment]
Ah, re-opened elsewhere.

**Comment by Uveso** [comment]
yeah, while i tried to rebase it, i wrecked github again :)

**Comment by aeoncleanse** [comment]
make changes on featurebranch
git checkout develop/BlackOps
git pull upstream
git checkout featurebranch
git rebase develop/BlackOps
git push -f

**Comment by Uveso** [comment]
Thanks a lot. i will try this next time :))

**Pull request closed without merging**
