### PR TITLE
Adding LOD calculation to ModBlueprint loop

### PR DESCRIPTION
**Pull request by Uveso**
#107

I added some remark lines, and you can change the LOD Settings for testing.

options:
1:
Only change the LOD settings and will hide units by size if you zoom out.

2:
Makes the same as 1 but only highres textures and models will be used.
It removes the 2nd LOD entry so the lowres textures and models are not loaded to memory.
And if you zoom out there is less or no stutter, because textures and models don't need to change.
This is a true UI-Lag fix :)

3:
Removes all LOD settings and never hide a unit. Also always using highres textures & model.
Looks good if you make a video or playing without strategic icons.

To bad we can't make ingame options. So we have to decide, what option we will hardcode there.
I think option 2 is the best. Less memory, no stutter and hiding units for better gamespeed.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
How much GPU impact do options 2 and 3 have? As I run a GTX 980 it's impossible for me to measure, the game runs at a solid 100FPS no matter what I do. Could someone with a less powerful system try running these and see if there's any negative impact?

This is a test for full FAF integration. For that, we will be able to make options. However, if differing options will desync the game, it's best we do not do that, and instead come up with a decision on which version of this is best.

**Comment by Uveso** [comment]
I have tested this with my PC's
I7@4,5GHz with GTX770
I7@4,2GHz with GTX560
and a Core2 Quadcore@2,5GHz with GTX560
I cant see any slowdown while using only higres textures and models (Option 2)
In fact it's faster while fast zooming in and out.

Option 3 has some CPU impact on the Quadcore CPU if i use more then 2000 Units and full zommed out. (Tested while all 3 PC are runing a LAN game)

So option 3 can have negative impact to the game, if the cpu is slow or the simspeed is lower then 0 in late game. And as i said before, it makes not really sense to display units under the strategic icon.

Option 2 is faster in all aspects. i would use this. But this should tested with some slower PC's.

**Comment by aeoncleanse** [comment]
Done some testing. Can you refine this PR such that option 2 is the only option, which should reduce the code length nicely :)

**Comment by Uveso** [comment]
I removed all debug stuff and option 2 is now hardcoded.
I don't deleted the remarklines. Maybe someone will find this usefull if we are vanished or dead :)

**Comment by Uveso** [comment]
Tested this with several multiplayer games now.
Option 3 has some problems with explosions, if zoomed out. So this is not a option for release at all.

All other games where tested with Option 2. (what we have hardcoded now)
Run's flawless. And the best of all, the fast in/out zoom-stutter is gone.
Also hiding units under the stategic icon works perfect.
And using the Highres model always makes the game indeed faster. Absurd, but i like it :)

So i can say, this is working without errors or display issues.
But we still have to check this on slow PC's.
Or we put this into the BO-Release version, and let the player test it :)))

**Comment by aeoncleanse** [comment]
Could you try to collate full system specs for all machines tested? I want to push this main-game, but people will fuss unless a wide variety of hardware was involved. I've got the high end covered, but we need your slower machines :p

**Comment by Uveso** [comment]
Well, here are my slower machines:

supcomtestings

PC1: Windows 7
Intel Core i7 4790K @4.4GHz
8GB DDR3 Ram @ 1600MHz
GeForce GTX770 @1140MHz
Ingame CPU Rating: 145

PC2: Windows 7
Intel Core i7 6700K @4.2 GHz
8gb DDR4 @1600MHz
GeForce GTX560Ti @950MHz
Ingame CPU Rating: 130

PC3: Windows 7
Intel Core2 Quad Q8400 @2,6GHz
8GB DDR2 @800MHz
GeForce GTX560Ti @822MHz
Ingame CPU Rating: 316

**Comment by aeoncleanse** [comment]
Cool. Can we get FPS stability and general feel for zooming with the hard-coded option on PCs 2 and 3? 560Ti is as weak a card as I think we need to worry about.

**Comment by Uveso** [comment]
Well i gues you tested it already by yourself.
There is no difference if i use the mod or not. Its just looking better, but don't affect GPU speed at all.
Its only using less memory inside every blueprint, whats making the simspeed slightly faster.

FPS stability is the same with or without the mod. In fact this was the whole point.
Better looking grafics, faster simspeed and no negative effect to the GPU.

So what exactly you want me to show ? 

Btw, we could make a test mod :)
[AdvancedLOD_V1.zip](https://github.com/aeoncleanse/Mods/files/402228/AdvancedLOD_V1.zip)

**Comment by aeoncleanse** [comment]
Using higher LODs means more polys to render. My GTX 980 isn't even going blink at anything this game ever throws at it, but with high unit count that increased rendering cost might hit something like a 560Ti

**Comment by Uveso** [comment]
I tested PC3 with an old GeForece640 card @650Mhz.
Same as before; I see no difference.

Maybe this is because we are hiding units under the strategic icon. There are almost the same Polygons to render then before, even with highres models, because we are displaying lesser units.

I can build a 4th PC with an AMD Dual Core Opteron 180 and a AGP-BUS-GeForce 9800GT if needed.
I only need to buy a CPU cooler for it.

**Comment by aeoncleanse** [comment]
No, I think that's enough. A 640 is a seriously weak card. Thanks a bunch :)

**Comment by Uveso** [comment]
Added a smal fix for special units like BuildBotEffect and Jammer Crystals.
There are 3 units where we should not set the IconFadeInZoom to 130. Because they dont have / need a strategic Icon.

**Pull request merged**
