### PR TITLE
Full AI support for BlcakOps

### PR DESCRIPTION
**Pull request by Uveso**
From issue  #102

This will add Templates for all units to enable sorian and normal AI unit handling.

Artemis and crabeggs are not working at the moment! All other units are fine.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Could you please clean up the content of these files? The lines of ***\* should be replaced by the following format at the top:

```
-----------------------------------------------------------------
-- Author(s):  Exavier Macbeth
-- Summary  :  BlackOps: Adv Command Unit - Serephim ACU
-- Copyright © 2005 Gas Powered Games, Inc.  All rights reserved.
-----------------------------------------------------------------
```

Also, can we keep file size to a minimum by getting rid of any unfilled sections. Thanks :)

**Comment by aeoncleanse** [comment]
I just restructured the branches on this repo to make some bloody sense, as I made it before I could really do git. Could you re-target this branch at the new develop/BlackOps branch please? Sorry for the trouble!

**Comment by Uveso** [comment]
These are not the final Ai scripts, because they need some balance.

``` LUA
            T4LandExperimental1 = {
                Seraphim = {'bsb2402', 10}, -- Haasioz-Iya (Seraphim Quantum Rift Archway) 
            },
```

You see the 10 after the unitID ? {'bsb2402', `10`}

This means 10% of all builded T4LandExperimental1 are Rift gates.
This should be reduced to 5% in this case.

Also all other units are on 50% exept the Tech3 Mass and Energy storage. They will be build to 100% if Tech3 is aviable.
I just released this so other ppl can use the ai to test the black ops mod.

Btw github isnt working now. Can't update or anything else. Will check this after sleeping :)

**Comment by Uveso** [comment]
Well i cant get github back to work like it was before.
Last time i cloned the repository i only got 2 directories; BO unleashed an ACU.

Now i get all those dir's like ExperiMENTALz,VetMod etc. They are now all inside my local mod dir.

I dont know how i can only get the 2 folders related to Black Ops.

**Comment by aeoncleanse** [comment]
Yup they're all there. It's fine. What you do is update it all, then make the changes on top, and direct it at  develop/BlackOps

**Comment by aeoncleanse** [comment]
You're right though, having a mod specific commit history was good. What I've decided to do now is have master have all the mods in there, then have a develop branch for each one where the other mods are removed in a commit.  We can then continue as before :)

**Comment by Uveso** [comment]
Oh yes, please. Because i clone it directly to my game/mod folder and don't need the other folders there.

**Pull request closed without merging**
