### PR TITLE
Fix Alle Race templates are not working with T3 MassStorage

### PR DESCRIPTION
**Pull request by Uveso**
If i create a template from MassStorage and try to use this with another race, this won't work.

This is because of wrong unit Names.

Names should be created with those rules:

```
The U for the original factions stands for UNITS. the next letter identifies the faction.
A= Aeon
E= Earth
R= Cybran
When FA came out X was added to the Units folder. The Seraphim faction is XS
UAA=Air
UAB=Buildings
UAC=Civilian Buildings
UAL=Land
UAS=Ships

Example Techlevel UEF Land factory:
ueb0101
ueb0201
ueb0301
```

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Not sure I want to be doing this. Why does the Sera T1 storage work in FAF when it begins with an X, if it has to start with a U? Why is this even needed? I need to check if this works, the all-faction template saving option should do away with this issue.

**Comment by CentauriSoldier** [comment]
Hi there, 
I'm not sure where to ask this question but could someone who's working on the FAF client add a line to the SupComDataPath.lua file (in /ProgramData/FAForever/bin) on the server-side? I have a mod that needs access to a certain file (Game.prefs) in the AppData directory due to the Lua state being restricted in regards to cFunctions. The math.random() function is not seeded properly in the Lua state containing the ModBlueprints() function (called by the RuleInit.lua). This disallows pseudo-random numbers to be generated; however, I have devised a way around this limitation but need to be able to read the Game.prefs file.

The line is as follows.
mount_dir(string.gsub(SHGetFolderPath('PERSONAL'), 'Documents', 'Appdata')..'Local\Gas Powered Games\Supreme Commander Forged Alliance', '')

I can add the line myself and make the file read-only but then I cannot get updates from FAF since the file can't be written to once it's tagged read-only.
Also, I have a work-around without writing that line but it requires using a junction in the game's install folder. It's not ideal since the user of the mod would also have to add a junction to his directory. I'd rather the mod just work without the user needing to do anything.

Additionaly, anyone else who wants pseudo-random numbers in this Lua state can get them by simply requiring my utility mod that creates the random number generator. This will open up an entirely new way to mod FA.

**Comment by Uveso** [comment]
@aeoncleanse 
F1 storage works, because the seraphim faction has the X instead of the U from game developer side.
This was accounted while making the `All race Template Mod`.

This is the related funktion:
constuction.lua line 2271 +

``` LUA
local function ConvertID(BPID)
    local prefixes = {
        ["AEON"] = {
            "uab",
            "xab",
            "dab",
        },
        ["UEF"] = {
            "ueb",
            "xeb",
            "deb",
        },
        ["CYBRAN"] = {
            "urb",
            "xrb",
            "drb",
        },
        ["SERAPHIM"] = {
            "xsb",
            "usb",
            "dsb",
        },
    }
    for i, prefix in prefixes[string.upper(currentFaction)] do
        if table.find(buildableUnits, string.gsub(BPID, "(%a+)(%d+)", prefix .. "%2")) then
            return string.gsub(BPID, "(%a+)(%d+)", prefix .. "%2")
        end
    end
    return false
end
```

As you can see, the `All Race Template` is based on renaming the first 3 letters of the unit.
I didnt see a clean way to inject functionality for BO named units without a double size of the prefix Array.
And because i only need those Mass/Energy storage to work with All faction templates i decided to chage the unitnames and not the function.

@CentauriSoldier 
Well yes this is the wrong place :) This special thread here is only related to the renaming of some units inside the Black Ops Mod.
The right place for FAF stuff is here:
https://github.com/FAForever/fa

Anyway, you can't use Random numbers inside `ModBlueprints()`. If you do so, you will instantly desync the game after loading into the gammeworld. All blueprints has checksumms and will be checked over all clients.
If you randomly change something, not all clients will make the same changes, because its random. This will lead always in desyncing the game.

In this case i dont think, we will make such changes inside initial game scripts.

BUT, if you want more information or just continue this conversation, please go to:
https://github.com/FAForever/fa/issues
Click there on `New issue` and continue writing there.

You can also start a forum thread here:
http://forums.faforever.com/viewforum.php?f=41

**Comment by CentauriSoldier** [comment]
Excellent. Thank you for that info, Uveso. I didn't realize the game would desync lol, that's good to know. I can fix that issue by making everyone have the same seed number, that won't be a problem. Thanks again.

**Comment by aeoncleanse** [comment]
Wait Uveso, this PR is to make another mod work? All race template mod?

**Comment by Uveso** [comment]
No :)
The original `All Race Template` modification was former a part of the GAZ_UI.
It's now implemented to the FAF version.

**Comment by aeoncleanse** [comment]
Adjust the code, not the unit names. Everything in BlackOps is B__XXXX. I don't see why this would need anything more than 4 more lines of code into the Prefix table.

**Comment by aeoncleanse** [comment]
Hang on. No. What we really want to do is adjust the primary FAF code to make it so the first letter doesn't matter. Shrink the table to AB, EB, RB, SB.

**Comment by Uveso** [comment]
ok then lets start :)

This is a table of all ingame prefixes:

``` LUA
Aeon={
  daa
  dal
  dalk
  uaa
  uab
  ual
  uas
  xaa
  xab
  xal
  xas
  zab
},
Cybran={
  dra
  drl
  drlk
  ura
  urb
  url
  urs
  xra
  xrb
  xrl
  xrs
  zrb
},
Seraphim={
  dslk
  xsa
  xsb
  xsl
  xss
  zsb
},
UEF={
  dea
  del
  delk
  uea
  ueb
  uel
  ues
  xea
  xeb
  xel
  xes
  zeb
}
```

If i shrinking it to units with Categories.STRUCTURE and only CanBeBuildFromPlayer:
This will left:

``` LUA
Aeon={ 
  uab
  xab
  zab
},
Cybran={ 
  urb
  xrb
  zrb
},
Seraphim={ 
  xsb
  zsb
},
UEF={ 
  ueb
  xeb
  zeb
}
```

We can ignore the "b" at the end. Templates are only available for buildings.

So we have:
u = Units from Supreme Commander
x = Units from Forged Alliance (so the x is not only for Seraphim)
z = FAF Factories

This is the old Prefix table and search loop: 

``` LUA
local function ConvertID(BPID)
    local prefixes = {
        ["AEON"] = {
            "uab",
            "xab",
            "dab",
        },
        ["UEF"] = {
            "ueb",
            "xeb",
            "deb",
        },
        ["CYBRAN"] = {
            "urb",
            "xrb",
            "drb",
        },
        ["SERAPHIM"] = {
            "xsb",
            "usb",
            "dsb",
        },
    }
    for i, prefix in prefixes[string.upper(currentFaction)] do
        if table.find(buildableUnits, string.gsub(BPID, "(%a+)(%d+)", prefix .. "%2")) then
            return string.gsub(BPID, "(%a+)(%d+)", prefix .. "%2")
        end
    end
    return false
end
```

Seraphim is using a non existent prefix "usb".
Also "dab","deb","drb" and "dsb" are not from the original game.
And it is missing the "z" for FAF factories.

This is my new function:

``` LUA
local function ConvertID(BPID)
    local Prefix = { ["Aeon"] = "a", ["UEF"] = "e", ["Cybran"] = "r", ["Seraphim"] = "s" }
    local FirstLetter = { "%1", "x", "u", "b" }
    for _, FL in FirstLetter do
        if table.find(buildableUnits, string.gsub(BPID, "(%a)(%a)(%a)(%d+)",FL..Prefix[currentFaction].. "%3%4")) then
            return string.gsub(BPID, "(%a)(%a)(%a)(%d+)",FL..Prefix[currentFaction].. "%3%4")
        end
    end
    return false
end
```

The new function is only replacing the 2nd letter for the faction.
This will find any unit with not changing the 1st letter like BlackOps, FAF Factories etc.
It will also manage the "dab","deb","drb" and "dsb" prefixes
If there is no unit found it will replace the first letter with U and X, and serach again.

The last search with "b" catch those units, who are from Forged Alliance that starts with "x" and has converted to "b". Like the UEF Tech3 PowerDefence (xeb2306) where only BO has Tech3 PD for the other races.

I am still testing this with all unitmods, but looks good so far.

**Comment by Uveso** [comment]
Found 2 units, who dont match the rules :)

```
Tech 1 Airstaging
bab5102
beb5102
brb5102
bsb5104 <- 4 instead of 2 at the end

Tech3 Shieldgenerator
uab4301
ueb4301
xsb4301
brb4207 <- 207 instead of 301
```

**Comment by aeoncleanse** [comment]
Fabulous work. You're going to have to teach me what the hell all this wacky string manip stuff does one day :p

**Comment by Uveso** [comment]
Maybe it will be clearer, if you see the real values handled by string.gsub

This is the gsub syntax:
string.gsub(`Source`, `Searchpattern`, `ReplaceWith`)

This is the gsub from our function:
NewBPID = string.gsub(BPID, "(%a)(%a)(%a)(%d+)",FL..Prefix[currentFaction].. "%3%4")

Now, the first value (%a) will be replaced with FL:
string.gsub(BPID, "`(%a)`(%a)(%a)(%d+)",`FL`..Prefix[currentFaction].. "%3%4")

And the 2nd (%a) will be replaced with Prefix[currentFaction]
string.gsub(BPID, "(%a)`(%a)`(%a)(%d+)",FL..`Prefix[currentFaction]`.. "%3%4")

%3 inside the RaplaceWith means, the 3rd value inside Searchpattern.
So we replace the 3rd (%a) with the 3rd value of the Searchpattern.
This will replace the 3rd (%a) with itself:
string.gsub(BPID, "(%a)(%a)`(%a)`(%d+)",FL..Prefix[currentFaction].. "`%3`%4")

Now guess, %4 is replacing the 4th value inside the Searchpatern (%d+)
The `+` inside `(%d+)` means, find a digit `%d` with any length `+`
string.gsub(BPID, "(%a)(%a)(%a)`(%d+)`",FL..Prefix[currentFaction].. "%3`%4`")

If we now fill all those variables with a real value:
XSB1012 = string.gsub(UEB1012, "(U)(E)(B)(1012)",X..S.. "B1012")

It's not magic :)

**Comment by aeoncleanse** [comment]
More i need to know wtf is meant by %char. Each one does something different and weird lol

**Comment by Uveso** [comment]
I made a PR on FAforever/FA:
https://github.com/FAForever/fa/pull/1400

So we don't need this PR anymore, because i don't want to rename the massstorage now :)))

**Pull request closed without merging**
