### PR TITLE
Fixes #97 BackgroundIcons wrong on some units

### LINKED ISSUE #97: BackgroundIcons are wrong on some units
```
 - Unit bab5205 Name: Sanctuary (Advanced Air Staging Facility) has a wrong BackgroundIcon: "amph"
   Please change (General.Icon = 'amph',) to (General.Icon = 'land',) in file [bab5205_unit.bp]

 - Unit beb1202 Name: HCPP - X2000 (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [beb1202_unit.bp]

 - Unit bab1202 Name: HC-2 (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [bab1202_unit.bp]

 - Unit brb1202 Name: HC-3 (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [brb1202_unit.bp]

 - Unit bsb1202 Name: Uya-atoh (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [bsb1202_unit.bp]

 - Unit beb1302 Name: HCPP - X3000 (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [beb1302_unit.bp]

 - Unit bab1302 Name: HC-3 (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [bab1302_unit.bp]

 - Unit bsb1302 Name: Uya-atoh (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [bsb1302_unit.bp]

 - Unit brb1302 Name: HC-3 (Hydrocarbon Power Plant) has a wrong BackgroundIcon: "land"
   Please change (General.Icon = 'land',) to (General.Icon = 'amph',) in file [brb1302_unit.bp]


```

### PR DESCRIPTION
**Pull request by lhigginbotham**
Fixes for Uveso's detected BackgroundIcons mismatches.  It doesn't seem to have any direct effect on base gameplay or visuals (maybe with a custom icon pack?), but this corrects it regardless.

(I don't really have any experience with modding Supreme Commander but this seemed like a simple enough fix.  If I missed something, let me know.)

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Fabulous, thanks!

**Comment by Uveso** [comment]
Thank's a lot lhigginbotham,

It has a visual effect!
Those backgroundicons are dispayed in the buildmenu

As example Unit BAB1302 Aeon Hydrocarbon Power Plant:
The old backgroundicon (land) looked like this: (the middle icon)
hydroland

And you changed it to `amph` (amphibious, because the Unit can also be build on Water)
Now with your change the icon look like this:
hydroamph

You can now see water in the lower right side of the icon.

**Comment by lhigginbotham** [comment]
Ooh, that's what that stands for.  I read that and went "amph? I bet that stands for ampere."  Which was then reinforced by all of the ones flagged to be changed to "amph" were hydrocarbon generators.  Thanks brain.

I appreciate the correction.

Although that does bring up a different point.  Should those generators have amphibious backgrounds?  I'm certainly not an expert, but I don't recall seeing hydrocarbon deposits in bodies of water.  If that's the case, then I think the T1 versions for all the hydrocarbon generators need to be changed as well (Unless that's also by design).

Please forgive my ignorance.

**Comment by Uveso** [comment]
There are some maps where you can build Massextractors and Hydros on water.

And you are absolutely right we have to change this on T1 Hydros as well.
And we did it in the main game:
https://github.com/FAForever/fa/commit/a2762096cb3cd2b4792ed3838260f7c50a70def6

Because the maingame has the T1 Hydro units, and black ops is adding T2 and T3 Hydro's. :)

**Pull request merged**
